blueye: # namespace

  ros2_interface_node: # node
    ros__parameters:
      # ROS- related params
      rate: 25.0 #Hz
      is_simulation: False
      use_gamepad: True
      
      # Blueye ROV-related params
      ## Camera params 
      #camera_bitrate: 6000000 # type: integer, range:1 000 000 - 16 000 000, unit: bits
      camera_bitrate_min: 1000000 
      camera_bitrate_max: 16000000 
      
      #camera_exposure: -1_ # type: int, range: 1 - 5 000, unit: [s], t_exp = N/1000[s], auto: exp=-1
      camera_exposure_min: -1
      camera_exposure_max: 5000
      
      #camera_framerate: 25 # type: int, values:{25, 30}, unit:fps
      camera_framerate_values: [25, 30]
      
      #camera_hue: 0 # type: int, range: -40 - 40, unit: ?
      camera_hue_min: -40
      camera_hue_max: 40      
            
      #camera_is_recording: 0 # type: bool 
      #camera_record_time: -1 # type: int, range: 0 - range(int), unit: [s], t=-1 if not recording
      
      #camera_resolution: 1080 # type: int, values={480, 720,1080} , unit: vertical_pixels
      camera_resolution_values: [480, 720,1080]
            
      #camera_whitebalance: -1 # type: int, range: [2800, 9300], unit: Kelvin
      camera_whitebalance_min: 2800 # auto: -1
      camera_whitebalance_max: 9300
      
      #camera_tilt_angle: 0  # type: float64, range: [30, 30], unit: [Â°] 
      camera_tilt_angle_min: -30
      camera_tilt_angle_max: 30
      
      #camera_tilt_speed: 0 # type: int, range: [-1, 1], unit: [] 
      camera_tilt_speed_min: -1
      camera_tilt_speed_max: 1
      
      ## Lights level limits, type: int, range: [0, 255], unit: []
      lights_level_min: 0
      lights_level_max: 255
      
      ## Lights change step when using gamepad
      lights_level_delta_perc: 10 # percent of the range
      lights_level_turn_on_perc: 50 # percent of the range
      
      ## Velocities forces limits: type: float, range: [-1, 1], unit: []
      velocity_force_min: -1
      velocity_force_max: 1
      
      ## Boost gain limits: type: float, range: [0, 1], unit: []
      boost_gain_min: 0.0
      boost_gain_max: 1.0
      
      ## Slow gain limits: type: float, range: [0, 1], unit: []
      slow_gain_min: 0.0
      slow_gain_max: 1.0
      
      ## Water densities: type: integer, unit: [grams/liter]
      ### fresh_water = 1000 g/l, Dead Sea = 1240 g/l
      density_fresh: 997
      density_brackish: 1011
      density_salty: 1025
      water_density_values: [ 997, 1011, 1025 ]
      water_density_min: 997
      water_density_max: 1240
      
            
      
       # type: , range: , unit: 
       # type: , range: , unit: 
       # type: , range: , unit:
        # type: , range: , unit: 
         # type: , range: , unit: 
          # type: , range: , unit: 
           # type: , range: , unit: 
            # type: , range: , unit: 
             # type: , range: , unit: 
             
              
 # type: , range: , unit: 
